brew "mas"

mas "1Password", id: 443987910
mas "Airmail 3", id: 918858936
mas "Day One", id: 1055511498
mas "MindNode 5", id: 1289197285
mas "Monosnap", id: 540348655
mas "Moom", id: 419330170
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "Reeder", id: 880001334
mas "Slack", id: 803453959
mas "Things", id: 904280696
mas "Tweetbot for Twitter", id: 557168941

cask "bartender"
cask "caskroom/versions/java8"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "little-snitch"
cask "sublime-text"
cask "vlc"

cask "caskroom/fonts/font-inconsolata-for-powerline"

brew "ag"
brew "ctags"
brew "elasticsearch", restart_service: :changed
brew "erlang"
brew "exenv"
brew "elixir-build"
brew "exercism"
brew "figlet"
brew "git"
brew "gutenberg"
brew "heroku"
brew "httpie"
brew "postgresql", restart_service: :changed
brew "pyenv"
brew "nvm"
brew "reattach-to-user-namespace"
brew "redis", restart_service: :changed
brew "rustup-init"
brew "tmux"
brew "vim"
brew "z"
brew "zsh"
brew "zsh-completions"

